AWSTemplateFormatVersion: 2010-09-09
Description: "Create ECS service for WS pull request"

Parameters:
  VpcId:
    Type: String
    Default: vpc-1ba6307c
  MainListenerARN:
    Type: String
    Description: The main load balancer listener that we going to add rules into
    Default: arn:aws:elasticloadbalancing:us-west-2:993316282153:listener/app/ed-web-Elb-K5SDEGBIWZP3/dc382608ece43558/79885aaf58de3ff8
  ListenerRulePriority:
    Type: Number
    Description: Unique number from 1 to 50000 to represent rule priority in listener
    Default: 10
  ECSClusterName:
    Type: String
    Description: ECS Cluster that we are going to add service into
    Default: staging
  GitSHA:
    Type: String
    
Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: ws-api-pr-staging
      Protocol: HTTP
      TargetType: instance
      Port: 80
      HealthCheckIntervalSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: 10
  
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions: 
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Sub pr-${GitSHA}.workstream.is
      ListenerArn: !Ref MainListenerARN
      Priority: !Ref ListenerRulePriority

  Ecs:
    Type: AWS::ECS::Service
    DependsOn:
      - ListenerRule
      - TargetGroup
    Properties:
      Cluster: !Ref ECSClusterName # TODO: Replace with script
      ServiceName: !Ref GitSHA
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
      SchedulingStrategy: REPLICA

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - 
          Name: web
          Image: amazon/amazon-ecs-sample # TODO: Replace with script
          MemoryReservation: 512
          Memory: 768
          PortMappings:
            -
              ContainerPort: 8080
              HostPort: 8080