AWSTemplateFormatVersion: 2010-09-09
Description: "Create ECS service for WS pull request"

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: vpc-1ba6307c # TODO: Replace with script
      Tags:
      - Key: Name
        Value: ws-api-pr-staging
      Protocol: HTTP
      TargetType: instance
      Port: 80
      HealthCheckIntervalSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: 10
  
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions: 
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions: 
        - Field: host-header
          HostHeaderConfig:
            Values:
              - pr3-staging.workstream.is
      ListenerArn: arn:aws:elasticloadbalancing:us-west-2:993316282153:listener/app/ed-web-Elb-K5SDEGBIWZP3/dc382608ece43558/79885aaf58de3ff8 # TODO: Replace with script
      Priority: 6 # TODO: Replace with script, need to be unique from 1 - 50000

  Ecs:
    Type: AWS::ECS::Service
    DependsOn:
      - ListenerRule
      - TargetGroup
    Properties:
      Cluster: staging # TODO: Replace with script
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
      SchedulingStrategy: REPLICA

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - 
          Name: web
          Image: amazon/amazon-ecs-sample # TODO: Replace with script
          MemoryReservation: 512
          Memory: 768
          PortMappings:
            -
              ContainerPort: 8080
              HostPort: 8080